server:
  port: 88

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.196.128:8848
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: product_route
          uri: lb://kiritomall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://kiritomall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://kiritomall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://kiritomall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: kiritomall_host_route
          uri: lb://kiritomall-product
          predicates:
            - Host=kiritomall.com,item.kiritomall.com

        - id: kiritomall_search_route
          uri: lb://kiritomall-search
          predicates:
            - Host=search.kiritomall.com

        - id: kiritomall_auth_route
          uri: lb://kiritomall-auth-server
          predicates:
            - Host=auth.kiritomall.com

  application:
    name: kiritomall-gateway

## 前端项目，/api
## http://localhost:88/api/captcha.jpg      http://localhost:8080/renren-fast/captcha.jpg
## http://localhost:88/api/product/category/list/tree      http://localhost:10000/product/category/list/tree

## lb:load balance负载均衡！！！
## predicates：断言！！！
## RewritePath：重写路径！！！