server:
  port: 10000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 121.5.68.208:8848
  application:
    name: kiritomall-product
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
#  mybatis-plus sql日志打印
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl