server:
  port: 30000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.196.128:8848
    alicloud:
      access-key: LTAI5tQxeBJTEc9H3xri5SFJ
      secret-key: KSBCPMyipXOh0qyygP6NfMtdx3niOU
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: kirito-mall

  application:
    name: kiritomall-third-party
