server:
  port: 8000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 121.5.68.208:8848
  application:
    name: kiritomall-member
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto